### ISSUE TITLE
The Status Bar does not reach the end of the screen.

### ISSUE THREAD

**Issue by carlsmith** [vigna/ne#49]
Whenever I use the Status Bar, it runs from the left side of the screen up to the last character on the right, but does not include it, so it looks under-scanned. I know I can use Fast GUI to hide it, but I don't like how that changes the menus.

It's a minor gripe, but every time I catch it out the corner of my eye, it makes me think something crazy has happened for a few milliseconds.

Thanks again for `ne`, and making all of our terminals nicer.

**Comment by vigna** [comment]
So, the problem is that you cannot always print that particular character. If you print it, _some_ terminals with the "automargin" property will scroll the whole screen.

I must admit that I haven't tested many terminals in the last 25 years, and both iTerm and Terminal on Mac and xterm on X do not have this problem. It is possible that by now no terminal has this problem.

The crux is in the tests at line 678 and 790 of term. c. If you kill there the part

     - (AutoWrap && curY == ne_lines - 1)

the last character will be printed.

If you want to give a shot, just do that edit and recompile. I'd be interested in knowing whether it works for you.

**Comment by vigna** [comment]
https://stackoverflow.com/questions/810483/unable-to-turn-off-automatic-margins-by-termcap-in-mac

**Comment by vigna** [comment]
https://github.com/vigna/ne/commit/68471d1c8e0a0895e71db72ddc6460ac85ee7a96
