### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by dodona2** [vigna/ne#50]
make PREFIX=/opt/ne build install
 cd doc; make )
/usr/local/share/doc
make[1]: Entering directory '/usr/local/share/doc'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/usr/local/share/doc'
make: *** [makefile:28: docs] Error 2

**Comment by 5p0ng3b0b** [comment]
same here

**Comment by utoddl** [comment]
What is your initial directory? Because `cd doc` should not place you into `/usr/local/share/doc` if there's a `doc` subdirectory in the directory you're already in. Is the environment variable `$CDPATH` set to something that includes maybe `/usr/local/share`? If so, try instead
```
CDPATH='' make PREFIX=/opt/ne build install
```
(And you might consider putting `.` at the front of your CDPATH.)

Also, it's likely that the `install` target is going to fail because you won't have write permissions in `/opt`. So you'll probably need
```
CDPATH='' make PREFIX=/opt/ne build
CDPATH='' sudo make PREFIX=/opt/ne install
```
Also, what OS is this happening on? More out of curiosity really, but if they are shipping a screwy environment that breaks `cd`, it's a distro to be on the lookout for.
