### ISSUE TITLE
docs for Paragraph

### ISSUE THREAD

**Issue by uvtc** [vigna/ne#62]
By default, `[p` runs the Paragraph command, and the menu agrees, but the docs for Paragraph says its `^[p` (ctrl-alt-p).

**Comment by uvtc** [comment]
Or am I reading that wrong? I see the same issue with other commands that use alt key combos...

**Comment by utoddl** [comment]
You aren't reading it wrong. There's just no right way to read or write it.

Line 803 of inputclass.c shows "ESC-p", and if you look around in the comments above that and count lines in hex, you'll see that that corresponds to ne's keycode 0x1f0. In fact, if you go to the command line (^k) and enter `keycode` with no parameters, you're prompted to hit a key, and ne responds with the key code in hex, the input class (which is probably not useful, since you can map commands to ALPHA class keys anyway -- maybe), and the associated command if there is one.

If you do that and and hit `Alt-p` -- and you're terminal is configured much the way mine is -- you'll get `Key Code: 0x1f0,  Input Class: COMMAND,  Assigned Command: PA`. And if you do it again and instead hit `Esc` followed immediately by `p` (and by immediately I mean in a time interval less than the current EscapeTime value), then you will have effectively created the custom escape sequence `ESC-p`, or as the menus spell it, `[p`, or with the shift key or CapsLock on `ESC-P` and `[P`. The lower-case version has the same keycode: `0x1f0` as `Alt-p`. The upper-case one is `0x1d0`, but it's also mapped to the `PA` command.

So we're a bit inconsistent on the spelling of these key sequences, but also there are multiple ways to generate the same char sequence, and ne has no way of knowing which key combinations you used to generate a given char sequence. A lot of them are trapped by the window manager or the terminal emulator for their own purposes before they ever get to ne.

The list of "bound keys" that `help` shows for a given command is dynamically generated. (This is in contrast to the indicated key mapping shown in the menus, which is static and baked in at compile time.) So when `help pa` says `Bound keys(s): ^[P ESC-^P ESC-P ESC-p`, it means if you have a way of generating those sequences (remember, not all keyboards have an `Alt` key ), and something between you and ne doesn't consume that sequence first, ne will invoke the PA command.

**Comment by uvtc** [comment]
Thanks for that background, Todd!

Also, I'd forgotton that Alt-P and "ESC P" yield the same keycode (0x1f0).

Likewise for Ctrl-Alt-P and "ESC Ctrl-P" (0x190).
