### ISSUE TITLE
[Feature Request] enhance MoveEOW

### ISSUE THREAD

**Issue by uvtc** [vigna/ne#65]
Currently, after MoveEOW takes you to (one past) the end of a word, repeated use of it does nothing. I propose that if you're already past the end of a word (that is, between words), then another use of MoveEOW would then take you to the end of the *next* word. (Note: if the cursor is somewhere in a word, then MoveEOW would behave just as it always has.)

This change would allow users to repeatedly move forward-by-word, analogous to NextWord, and would also allow users to move forward- and back-by-word in the same manner that most GUI apps support (I have the commands mapped to Ctrl-Right/Left arrow keys). I noticed recently that the bash shell supports this style of -by-word navigation as well.

The docs for MoveEOW say, "moves the cursor one character past the end of the current word.". If the cursor has been moved one character past the end of the current word, then by definition, the cursor no longer *has* a current word (since the cursor is now actually between words).

Finally, if a user already has the cursor one past the end of a word, and they exec MoveEOW, they presumably *want* to move the cursor to (past) the end of *some* word, and the only one that makes sense is the next word in front of the cursor.

**Comment by uvtc** [comment]
See also discussion at: <https://groups.google.com/forum/#!topic/niceeditor/DHPpdNXJuSo>.

**Comment by utoddl** [comment]
We do need a way to consistently move forward and backward by words, and ending up at the start of those words or at their ends. But MoveEOW isn't the way to do that. It's used in macros to ensure you're at the end of the current word. We don't want it to start advancing us through the document.

I'm leaning toward either a NextWordEnd and PrevWordEnd that work like NextWord and PrevWord but landing you on the end of the words rather than the beginning, or adding an optional parameter to NextWord and PrevWord to indicate you want to land on the end rather than the beginning. I don't particularly like complicating the "one command, one parameter" thing, but I don't like adding command any more either.

Anyway, this would give you the effect you want without breaking MoveEOW. (While we're at it, there should also be a MoveSOW that's analogous to MoveEOW: if you're already there, it doesn't move you at all.)

**Comment by utoddl** [comment]
PrevWord and NextWord now have optional "<" and ">" parameters to indicate which end of the previous or next word you and to end on. With that, the needs expressed in this issue should be sufficiently addressed. Closing. Feel free to re-open if issues remain.
