### ISSUE TITLE
CTRL opens menu

### ISSUE THREAD

**Issue by HerrAugust** [vigna/ne#74]
On my laptop, pressing CTRL+ arrow opens the menu, even Fn + CTRL + arrow does the same. This is really uncomfortable. The behaviour I would expect is instead to select the next word.

**Comment by utoddl** [comment]
Javascript programs, either in a browser or stand-alone, can elect
to receive keyboard input as a stream of KeyboardEvent objects.
These have a set of booleans which indicate whether control, alt,
or meta keys were held down during the KeyboardEvent. Windows,
MacOS, or various XWindows and other environments for "native"
applications provide similar mechanisms.

Console applications like ne have none of that. Their view of the
outside world is limited to environment variables, signals, and a
stream of bytes coming in serially through a "tty" device. The
range of possible byte values is far too limited to encompass all
the combinations of buttons on modern keyboards with all their
shift, ctrl, and meta modifiers.

Each particular terminal emulator (hardly anybody uses actual
physical tty terminals any more) translates the key combinations
you press into byte sequences and feeds them into the tty where
console applications can read them one byte at a time. Console
applications examine the byte stream an attempt to derive what the
user did, essentially reversing the key-presses-to-bytes encoding
that the terminal emulator did earlier.

Console applications have three ways to reconstruct keystrokes from the
byte streams provided by terminals or terminal emulators:
(1) terminfo, (2) termcap, and (3) internally hard-coded byte
streams. Terminfo is preferred. Termcap is an older implementation
of the same idea. Hard-coded byte streams are a fallback for when
the terminfo or termcap terminal descriptions are either wrong
(which, odly enough, is still extremely common for the Backspace
and Delete keys!) or when describing key combinations that are
simply not accounted for in termcap or terminfo.

These byte streams basically fall into three classes: control codes
(single bytes with numerical values below 32), ASCII characters
(between 32 and 127), and "escape sequences" which are the ESC
character (#27) followed by any number of other bytes that together
define some combination of key presses. (I'm ignoring "high-ASCII"
-- single bytes numerically between 128 and 255 because this answer
is already way too long and I'm not half done yet.)

Control codes are so called because they used to control Teletype
hardware. For example, the BEL character (numerical value 7, a.k.a.
"Control-G" or "^G") used to ring a physical bell. ASCII characters
are the most boring subset of the most plain alphabet imaginable by
the isolated Americans who made it up. Escape sequences are just
that: ESC followed by a sequence of other bytes.

Ne uses the ESC character to activate or close its menu. It must
distinguish between a lone ESC versus the first character of an
escape sequence, which it does in two ways. First, if ne reads ESC
from the tty and no other characters arrive within the EscapeTime
(which defaults to one second), then it assumes you hit the Escape
key. On the other hand, if other characters arrive less than one
second later, ne examines all the escape sequences it knows about
-- those from terminfo or termcap, as well as any you may have
defined in your ~/.ne/.keys file. If it finds no matching escape
sequence, it assumes a bare ESC, and the following bytes are
examined individually. If it does find a matching escape sequence,
then it acts accordingly on the whole sequence as if it were a
single key stroke.


That's a lot of background, but necessary to understand what you
see when you hit "Control-CursorRight" on your keyboard. Your
terminal emulator creates an escape sequence which isn't in the
terminfo definition for your terminal. In fact, it isn't in the
terminfo definition for _any_ terminal. There's no way in terminfo
to say "escape sequence 'X Y Z' means 'Control-RightArrow'". It's
simply not there!

On my machine, with the terminal I usually use, I also get the menu
if I hit 'Control-RightArrow'. What's happening is, my terminal
emulator is generating an unrecognized escape sequence, so ne is
interpreting the leading ESC as a stand-alone Escape key -- which
activates the menu -- followed by some other characters which,
fortunately, don't select anything destructive in the newly
activated menu.

However if I bring up the command line (with ^K), enter the
"KeyCode" command, and hit 'Control-RightArrow', I get the
following text inserted into my document:

   `[1;5C`

What ne actually saw was ESC followed by "[1;5C". That matched no
known escape sequence, so it took the leading ESC as a lone Escape,
which cancelled my KeyCode command. The following characters were
inserted into the document because it looks to ne like I typed them
_really_ fast!

Using this technique, we can see the undefined escape sequences
that our terminal emulators are generating for these keys. For
mine, I get:

```
   Control-CursorUp     ESC [1;5A
   Control-CursorDown   ESC [1;5B
   Control-CursorRight  ESC [1;5C
   Control-CursorLeft   ESC [1;5D
```

The canonical way to write escape sequences like the ones above is
"\x1b[1;5A". You can use them in your ~/.ne/.keys file to
effectively hard-code escape sequences -- like these that terminfo
can't express -- and map them into ne key codes. Then you can map such
key codes to ne commands. For example I could add the following to
my ~/.ne/.keys file:

```
   # Control-CursorRight -> NextWord
   SEQ "\x1b[1;5C"   14A
   KEY 14A           NextWord
```

This is discussed in the ne manual under section 5.1 Key Bindings.

**Comment by HerrAugust** [comment]
Thank you for your gentle and exhaustive explanation. Writing in the ~/.ne/.keys file the following string actually works. However, I cannot find the binding for PreviousWord, corresponding to "\x1b[1;5D". Could you write that down as well?

   # Control-CursorRight -> NextWord
   SEQ "\x1b[1;5C"   14A
   KEY 14A           NextWord

**Comment by utoddl** [comment]
Exhaustive, but incomplete. I covered what goes into "SEQ" (input byte sequence) definitions pretty well, but I didn't cover "KEY" really at all.

Frankly, I don't know if this applies to other programs, but ne has this notion of 512 "virtual keys". (See the source file inputclass.c for the details.) Each of these has a "class" -- one of "ALPHA", "COMMAND", "RETURN", "TAB", "IGNORE", or "INVALID". However, I'm not convinced that distinction is particularly enlightening, because you can map pretty much any of the 512 virtual key codes to an arbitrary command string.

Looking at line 211 of inputclass.c, I see that the built-in command mapping for KEY 14A is "H", the abbreviated form of the "Help" command, and from the comment I see it's also the virtual key code that the F10 key's escape sequence gets mapped to. So in my example from the prior post, "KEY 14A NextWord" re-maps the F10 key from the "Help" command to the "NextWord" command. You can see that if you don't have the "KEY 14A" entry in your ~/.ne/.keys file, and then enter
```
KeyCode 0x14a
```
in ne's command line. It reports "Key Code: 0x14a,  Input Class: ALPHA,  Assigned Command: H". Probably not what you were after.

You can either map a block of the 512 keys you don't normally use, or find some that are not assigned by default and map them. There's a block starting at 14b that's available. Or better yet, map your SEQ to a KEY code that's already mapped to the correct key. If you do
```
help nextword
```
you'll see there's already nearly half a dozen KEYs mapped to that command. You can use one of them.

**Comment by HerrAugust** [comment]
Thank you again for your kind explanation. In my laptop, whose keyboard contains also a number-only part (like this: ), I inserted bindings for `CTRL + <-`, `CTRL + ->`, `CTRL + INIT`, `CTRL + END` (as you would use them in Windows Notepad, for example). Here is the content of my `~/.ne/.keys` file:

`
SEQ "\x1b[1;5C"   14A
KEY 14A           NextWord
SEQ "\x1b[1;5D"   14D
KEY 14D           PrevWord
SEQ "\x1b[1;5F"   14E
KEY 14E           MoveEOF
SEQ "\x1b[1;5H"   14F
KEY 14F           MoveSOF
`
