### ISSUE TITLE
Show selected text

### ISSUE THREAD

**Issue by nereusx** [vigna/ne#9]
When I select a text, I cant see what text is selected.
Reversing the color is an easy good idea.

**Comment by vigna** [comment]
Hey, thanks, we never thought about it! :)

**Comment by pepa65** [comment]
Hope you're not being sarcastic..?

**Comment by utoddl** [comment]
[sigh] Of all the things The Internet is good far, sarcasm isn't one of them. (There was a smiley-face!)

Truly, this is the number one most requested feature ever. And I agree with nereusx: "Reversing the color is an easy good idea." However, implementing that idea, given the way ne works, is anything but easy. In fact, I've been thinking about the problem since 1996, and I'm no closer to solving it now than I was then, mostly for the same reason implementing "wrap-long-lines" has never happened. The way lines are maintained and displayed in ne just doesn't lend itself to such "easy" changes. It could be done of course, but the changes would be quite invasive. If you can pull it off without breaking anything else and still preserve the simplicity of ne's architecture, then good on you.

**Comment by nereusx** [comment]
It was no sarcasm, it is work that need to do... closed or not, still needed to do.
I am confused; do you want or not, people to participated with this project?

I have several ideas about how to solve it but better to read the code first.

Thank you

**Comment by carlsmith** [comment]
Is it possible to reverse the *character* that the mark begins from? Even just being able to see 'the mark' and the cursor would help with visualising the selection.

**Comment by pepa65** [comment]
But it is better than nothing at all. The cursor will move if there is any input, the mark will only disappear when there is an action on the selected text (or an unmark). And if a user has forgotten which one is the mark, an arrow-key will quickly show which is the cursor. But it is much easier to forget where the mark was!!

**Comment by vigna** [comment]
The starting point of the block isnow highlighted.
